---
- name: Copy config files
  import_tasks: copy_config_files.yml
  tags: update-only

- name: Initialize control plane
  import_tasks: init_control_plane.yml

- name: Set up kubeconfig
  import_tasks: setup_kubeconfig.yml

- name: Install kube-bench
  import_tasks: install_kube_bench.yml
