---
- name: Reload sysctl
  command: sysctl --system

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true

- name: Restart NetworkManager (Cilium fix)
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Reexec systemd
  ansible.builtin.command: systemctl daemon-reexec
