---
- name: Add Pi hosts to SSH config file
  blockinfile:
    path: "~/.ssh/config"
    create: yes
    mode: "0600"
    block: |
      {% for host in groups['all_nodes'] %}
      Host {{ host }}
        HostName {{ host }}
        User {{ ssh_username }}
        IdentityFile ~/.ssh/id_darth_homekube
        StrictHostKeyChecking accept-new

      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HOMEKUBE PI HOSTS"
  become: false
