---
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

applicationSet:
  replicaCount: 1
configs:
  cm:
    create: true
    url: "https://192.168.86.241"
    oidc.config: |
      name: Google (via Dex)
      issuer: https://pi0.taild13083.ts.net/dex
      clientID: argocd
      clientSecret: argocd-dex-client-secret
      rootCA: |
        -----BEGIN CERTIFICATE-----
        MIIBcDCCARagAwIBAgIUSf9VR+890wUgUZ1h8wCRr6GA7uwwCgYIKoZIzj0EAwIw
        FjEUMBIGA1UEAxMLaG9tZWt1YmUtY2EwHhcNMjYwNjE3MDQ1MDMyWhcNMzYwNjE0
        MDQ1MDMyWjAWMRQwEgYDVQQDEwtob21la3ViZS1jYTBZMBMGByqGSM49AgEGCCqG
        SM49AwEHA0IABPQeFiJdqorOUyttROs9KRaYAijiazWfsBPVVa7xrBgihA/pY3mK
        Is4OXPgh7XIxFszEj6B3Waq7sVtveJuwGU2jQjBAMA4GA1UdDwEB/wQEAwICpDAP
        BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQPA6nWBdIzpaLGXrwAK/7BywHxfzAK
        BggqhkjOPQQDAgNIADBFAiAqQsWCyR89x9zOhJ+2gWEBDEcWRVkcfc+rYYuPVQDo
        cgIhAPoIHcIx/+8VDaNFmE7EtKWzB9EcqE+nTpdwX/tcwIqv
        -----END CERTIFICATE-----
      requestedScopes:
        - openid
        - profile
        - email
      requestedIDTokenClaims:
        email:
          essential: true
  rbac:
    create: true
    policy.default: ""
    scopes: '[email, groups]'
    policy.csv: |
      g, jan.groth.de@gmail.com, role:admin
controller:
  replicas: 1
  metrics:
    enabled: true
dex:
  enabled: false
redis:
  exporter:
    enabled: true
  metrics:
    enabled: true
repoServer:
  replicas: 1
server:
  replicas: 1
  metrics:
    enabled: true
