---
- name: Ensure /etc/kubernetes directory exists
  file:
    path: /etc/kubernetes
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy kubernetes resolv.conf with public DNS
  copy:
    dest: /etc/kubernetes/resolv.conf
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8
    owner: root
    group: root
    mode: "0644"
