---
#
# networking and kernel modules
#
- name: Copy kernel modules configuration
  copy:
    src: modules-load/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    backup: false
    owner: root
    group: root
    mode: "0644"

- name: Ensure overlay kernel module is loaded
  community.general.modprobe:
    name: overlay

- name: Ensure br_netfilter kernel module is loaded
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Copy sysctl configuration
  copy:
    src: sysctl/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    backup: false
    owner: root
    group: root
    mode: "0644"
  notify: reload sysctl

- name: Ensure journald drop-in directory exists
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Enable persistent systemd journal
  ansible.builtin.copy:
    dest: /etc/systemd/journald.conf.d/persistent.conf
    content: |
      [Journal]
      Storage=persistent
    owner: root
    group: root
    mode: "0644"
  notify: restart journald
