---
- name: Get Kubernetes package version information
  vars:
    k8s_components:
      - containernetworking-plugins
      - kubeadm
      - kubectl
      - kubelet
      - runc
  block:
    - name: Get package information
      command: "apt-cache policy {{ item }}"
      register: pkg_version_output
      changed_when: false
      failed_when: pkg_version_output.rc != 0
      loop: "{{ k8s_components }}"

    - name: Print version information
      debug:
        msg: "{{ item }} - {{ pkg_version_output.results[idx].stdout_lines[1] }} - {{ pkg_version_output.results[idx].stdout_lines[2] }}"
      loop: "{{ k8s_components }}"
      loop_control:
        index_var: idx

- name: Get containerd version
  command: "containerd --version"
  register: containerd_installed_version
  changed_when: false
  failed_when: containerd_installed_version.rc != 0

- name: Print containerd version information
  debug:
    msg: "containerd - installed: {{ containerd_installed_version.stdout }} | configured: v{{ containerd_version }}"
