---
# this works around a problem where raspberry pi unloads networking modules and CNI funcionality breaks
- name: Run tcpdump network diagnostics on wlan0
  command: tcpdump -i wlan0 -c2
  register: tcpdump_output
  ignore_errors: true
  changed_when: false
