---
- name: Retarget Kubernetes apt repository
  import_tasks: retarget_kube_apt_repo.yml

- name: Update apt packages
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    autoclean: true
    autoremove: true

- name: Install common packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - dnsutils
      - figlet
      - git
      - gpg
      - htop
      - jq
      - kubectx
      - net-tools
      - netcat-openbsd
      - nmap
      - tcpdump
      - traceroute
      - tree
      - vim
      - yq
    state: present
  register: _common_pkgs
  changed_when: >-
    (_common_pkgs.stdout | default('')) | length > 0 and
    '0 upgraded, 0 newly installed' not in (_common_pkgs.stdout | default(''))

- name: Remove /etc/motd
  file:
    path: /etc/motd
    state: absent

- name: Configure motd 1/2
  copy:
    src: system/motd-hostname
    dest: /etc/update-motd.d/20-hostname
    owner: root
    group: root
    mode: "0755"

- name: Configure motd 2/2
  copy:
    src: system/motd-updates
    dest: /etc/update-motd.d/20-updates
    owner: root
    group: root
    mode: "0755"

- name: Copy .bashrc for root
  copy:
    src: system/bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: "0644"

- name: Copy .bash_aliases for root
  copy:
    src: system/bash_aliases
    dest: "/root/.bash_aliases"
    owner: root
    group: root
    mode: "0644"

- name: Copy .bashrc for user
  copy:
    src: system/bashrc
    dest: "/home/{{ ssh_username }}/.bashrc"
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"
    mode: "0644"

- name: Copy .bash_aliases for user
  copy:
    src: system/bash_aliases
    dest: "/home/{{ ssh_username }}/.bash_aliases"
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"
    mode: "0644"
