---
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Kubernetes apt repository key
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[:2] | join('.') }}/deb/Release.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true
  changed_when: false

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[:2] | join('.') }}/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes

- name: Update apt packages
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes

- name: Install common packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - dnsutils
      - figlet
      - git
      - gpg
      - htop
      - jq
      - kubectx
      - net-tools
      - netcat-openbsd
      - nmap
      - tcpdump
      - traceroute
      - tree
      - vim
      - yq
    state: present

- name: Remove /etc/motd
  file:
    path: /etc/motd
    state: absent

- name: Configure motd 1/2
  copy:
    src: system/motd-hostname
    dest: /etc/update-motd.d/20-hostname
    owner: root
    group: root
    mode: "0755"

- name: Configure motd 2/2
  copy:
    src: system/motd-updates
    dest: /etc/update-motd.d/20-updates
    owner: root
    group: root
    mode: "0755"

- name: Copy .bashrc for root
  copy:
    src: system/bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: "0644"

- name: Copy .bash_aliases for root
  copy:
    src: system/bash_aliases
    dest: "/root/.bash_aliases"
    owner: root
    group: root
    mode: "0644"

- name: Copy .bashrc for user
  copy:
    src: system/bashrc
    dest: "/home/{{ ssh_username }}/.bashrc"
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"
    mode: "0644"

- name: Copy .bash_aliases for user
  copy:
    src: system/bash_aliases
    dest: "/home/{{ ssh_username }}/.bash_aliases"
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"
    mode: "0644"
