---
- name: Setup CNI (Cilium) on Kubernetes cluster
  hosts: pi0
  become: false
  gather_facts: true
  vars:
    local_kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/homekube.config"
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/homekube.config"
  roles:
    - cni
